const app=document.querySelector('#app');const KEY='mitsunoHaccpV1';let db=JSON.parse(localStorage.getItem(KEY)||'{"harvests":[],"bottles":[],"sales":[]}');const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const checks=['体調は良い？','手洗い・清潔な服装はOK？','作業台はきれい？','道具は洗って乾いている？','巣板にカビ・虫・汚れはない？','変な臭い・異物はない？','床・水・汚れに触れていない？','清潔で乾いた容器に入れた？'];
function shell(title,body){app.innerHTML=`<div class="brand">小さな蜜の舎</div><div class="hero"><h1>${title}</h1><p>採蜜・HACCP衛生管理</p></div>${body}`}
function home(){shell('HACCP管理',`<div class="grid"><div class="card" onclick="page('harvest')">🍯<b>今日の採蜜</b><small>チェックして記録</small></div><div class="card" onclick="page('records')">▤<b>記録を見る</b><small>ロットを確認</small></div><div class="card" onclick="page('bottle')">🫙<b>瓶詰め</b><small>製品ロットを登録</small></div><div class="card" onclick="page('stock')">📦<b>在庫・販売</b><small>本数を管理</small></div><div class="card wide"><b>現在の記録</b><small>採蜜 ${db.harvests.length}件 ／ 瓶詰め ${db.bottles.length}件 ／ 販売 ${db.sales.length}件</small></div></div>`)}
function harvest(){let d=new Date().toISOString().slice(0,10);shell('今日の採蜜',`<div class="field"><label>採蜜日</label><input id="date" type="date" value="${d}"></div><div class="field"><label>巣箱番号</label><input id="hive" placeholder="例：A-03"></div><div class="field"><label>採蜜量（kg）</label><input id="kg" type="number" step="0.1" placeholder="例：5.2"></div><h2 class="section">かんたんチェック</h2>${checks.map((x,i)=>`<label class="check"><input class="ck" type="checkbox"><span>${i+1}. ${x}</span></label>`).join('')}<div class="field"><label>メモ・異常</label><textarea id="memo" rows="3"></textarea></div><button class="action primary" onclick="saveHarvest()">採蜜記録を保存</button>`)}
function saveHarvest(){let date=q('date').value,hive=q('hive').value.trim(),kg=q('kg').value;if(!hive)return alert('巣箱番号を入れてください');let ok=[...document.querySelectorAll('.ck')].filter(x=>x.checked).length;let lot=date.replaceAll('-','').slice(2)+'-'+hive.toUpperCase();db.harvests.unshift({id:Date.now(),date,hive,kg,lot,ok,total:checks.length,memo:q('memo').value});save();shell('保存しました',`<div class="card"><small>採蜜ロット</small><div class="lot">${lot}</div><p class="${ok===checks.length?'ok':'danger'}">チェック ${ok}/${checks.length}</p><p>巣箱 ${hive} ／ ${kg||'-'} kg</p></div><button class="action primary" onclick="page('bottle')">次へ：瓶詰め</button>`)}
function bottle(){let opts=db.harvests.map(x=>`<option value="${x.lot}">${x.lot}（${x.hive}）</option>`).join('');shell('瓶詰め',db.harvests.length?`<div class="field"><label>採蜜ロット</label><select id="src">${opts}</select></div><div class="field"><label>内容量（g）</label><input id="grams" type="number" value="300"></div><div class="field"><label>本数</label><input id="count" type="number" placeholder="例：20"></div><button class="action primary" onclick="saveBottle()">瓶詰めを保存</button>`:`<div class="empty">先に採蜜記録を作ってください。</div>`)}
function saveBottle(){let src=q('src').value,grams=+q('grams').value,count=+q('count').value;if(!count)return alert('本数を入れてください');let lot='P-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+String(db.bottles.length+1).padStart(2,'0');db.bottles.unshift({id:Date.now(),date:new Date().toISOString().slice(0,10),src,grams,count,lot});save();shell('瓶詰め完了',`<div class="card"><small>製品ロット</small><div class="lot">${lot}</div><p>${grams}g × ${count}本</p><p>採蜜ロット：${src}</p></div>`)}
function records(){let all=db.harvests.map(x=>`<div class="item"><b>🍯 ${x.lot}</b><br><small>${x.date}・巣箱 ${x.hive}・${x.kg||'-'}kg・チェック ${x.ok}/${x.total}</small></div>`).join('');shell('記録',all||'<div class="empty">まだ採蜜記録がありません。</div>')}
function stock(){let made=db.bottles.reduce((a,x)=>a+x.count,0),sold=db.sales.reduce((a,x)=>a+x.count,0),left=made-sold;let opts=db.bottles.map(x=>`<option value="${x.lot}">${x.lot}</option>`).join('');shell('在庫・販売',`<div class="grid"><div class="card"><small>製造</small><b>${made}本</b></div><div class="card"><small>残り</small><b>${left}本</b></div></div><h2 class="section">販売を記録</h2>${db.bottles.length?`<div class="field"><label>製品ロット</label><select id="saleLot">${opts}</select></div><div class="field"><label>販売本数</label><input id="saleCount" type="number"></div><div class="field"><label>販売先・注文番号</label><input id="dest" placeholder="例：BASE #1234"></div><button class="action primary" onclick="saveSale()">販売を保存</button>`:'<div class="empty">瓶詰め記録がありません。</div>'}`)}
function saveSale(){let count=+q('saleCount').value;if(!count)return alert('販売本数を入れてください');db.sales.unshift({id:Date.now(),date:new Date().toISOString().slice(0,10),lot:q('saleLot').value,count,dest:q('dest').value});save();stock()}
function q(id){return document.getElementById(id)}function page(p){({home,harvest,records,stock,bottle}[p]||home)()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');home();
